from tkinter import *
win=Tk()
win.title("计算器")
def mathinput():
  print("1")
win.geometry("300x500")
win.configure(bg="white")
win.maxsize(300,500)
result=Entry(win,width=300,relief="groove")
result.place(width=300,height=125,x=0,y=0)
left=Button(win,text="(",font="Times 18 bold",relief="groove",command=mathinput,bg="grey").place(width=75,height=75,x=0,y=125)
right=Button(win,text=")",font="Times 18 bold",relief="groove",command=mathinput,bg="grey").place(width=75,height=75,x=75,y=125)
btn0=Button(win,text="0",font="Times 18 bold",relief="groove",command=mathinput).place(width=75,height=75,x=0,y=425)
dot=Button(win,text=".",font="Times 18 bold",relief="groove",command=mathinput).place(width=75,height=75,x=75,y=425)
equal=Button(win,text="=",font="Times 18 bold",relief="groove",command=mathinput).place(width=75,height=75,x=150,y=425)
plus=Button(win,text="+",font="Times 18 bold",relief="groove",command=mathinput,bg="grey").place(width=75,height=75,x=225,y=200)
minus=Button(win,text="-",font="Times 18 bold",relief="groove",command=mathinput,bg="grey").place(width=75,height=75,x=225,y=275)
multiply=Button(win,text="×",font="Times 18 bold",relief="groove",command=mathinput,bg="grey").place(width=75,height=75,x=225,y=350)
divide=Button(win,text="/",font="Times 18 bold",relief="groove",command=mathinput,bg="grey").place(width=75,height=75,x=225,y=425)
back=Button(win,text="←",font="Times 18 bold",relief="groove",command=mathinput,bg="grey").place(width=75,height=75,x=225,y=125)
clear=Button(win,text="clear",font="Times 18 bold",relief="groove",command=mathinput,bg="grey").place(width=75,height=75,x=150,y=125)
btn1=Button(win,text="1",font="Times 18 bold",relief="groove",command=mathinput).place(width=75,height=75,x=0,y=350)
btn2=Button(win,text="2",font="Times 18 bold",relief="groove",command=mathinput).place(width=75,height=75,x=75,y=350)
btn3=Button(win,text="3",font="Times 18 bold",relief="groove",command=mathinput).place(width=75,height=75,x=150,y=350)
btn4=Button(win,text="4",font="Times 18 bold",relief="groove",command=mathinput).place(width=75,height=75,x=0,y=275)
btn5=Button(win,text="5",font="Times 18 bold",relief="groove",command=mathinput).place(width=75,height=75,x=75,y=275)
btn6=Button(win,text="6",font="Times 18 bold",relief="groove",command=mathinput).place(width=75,height=75,x=150,y=275)
btn7=Button(win,text="7",font="Times 18 bold",relief="groove",command=mathinput).place(width=75,height=75,x=0,y=200)
btn8=Button(win,text="8",font="Times 18 bold",relief="groove",command=mathinput).place(width=75,height=75,x=75,y=200)
btn9=Button(win,text="9",font="Times 18 bold",relief="groove",command=mathinput).place(width=75,height=75,x=150,y=200)
win.mainloop()